baseurl = "https://joshdsblog.netlify.com/"
languageCode = "en-us"
title = "Josh Daniel's Blog"
# Define how many pages appear per site
paginate = 10
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Josh Daniel"
    site_description = "Data Science Blog."
    location = "Mercyhurst University"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Josh Daniel's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []


[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "joshdaniel7117"
    gplus     = ""
